spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mwanzo}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:mwanzo123}
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: true  # Enable to catch errors
    user: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:mwanzo123}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mwanzo}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: "/apidocs"
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework: INFO
