spring:
  datasource:
    url: ${DATABASE_URL}
    username: {DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false
  jpa:
    show-sql: false

springdoc:
  api-docs:
    path: "/apidocs"