services:
  api:
    container_name: "mwanzo"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - mwanzo_network
    volumes:
      - ./application.yaml:/app/application.yaml:ro

  postgres-db:
    image: postgres:15
    container_name: "postgres-mwanzo"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mwanzo_network

networks:
  mwanzo_network:

volumes:
  postgres_data:
