services:
  api:
    container_name: mwanzo
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - mwanzo_network
    volumes:
      # Mount config only as read-only.
      - ./application.yaml:/app/application.yaml:ro

  postgres-db:
    image: postgres:15
    container_name: postgres-mwanzo
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mwanzo_network
    volumes:
      # Named volume for persistence.
      - postgres_data:/var/lib/postgresql/data

networks:
  mwanzo_network:

volumes:
  postgres_data:
    driver: local
