version: "3.9"
services:
  jenkins:
    image: jenkinsci/jenkins:lts
    container_name: jenkins-container
    restart: always
    ports:
      - "8080:8082"
      - '50000:50000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/data/jenkins/jenkins_home:/var/jenkins_home'
    environment:
      - "JENKINS_OPTS=--prefix=/jenkins"
  api:
    container_name: "mwanzo"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_URL
      - FLYWAY_ENABLED
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - mwanzo_network
    volumes:
      - ./application.yaml:/app/application.yaml:ro
  postgres-db:
    image: postgres:latest
    container_name: "postgres-mwanzo"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mwanzo_network
networks:
  mwanzo_network:
volumes:
  postgres_data: