spring.application.name=Mwanzo

# JWT configuration
application.security.jwt.secret-key=kX8E5xJYJ9q1sQ0WzH1bT0oC2k1pZbKc4vNm3rFj7hYqD9lM6uXaWz+
application.security.jwt.expiration=3600000         
application.security.jwt.refresh-token.expiration=604800000  

