CREATE TABLE member
(
    member_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    members_name      VARCHAR(255)                            NOT NULL,
    member_type       VARCHAR(255)                            NOT NULL,
    registration_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    registration_fees DECIMAL                                 NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    exit_notice_date  TIMESTAMP WITHOUT TIME ZONE,
    exit_date         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_member PRIMARY KEY (member_id)
);