CREATE TABLE contribution
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id               BIGINT,
    contribution_date       TIMESTAMP WITHOUT TIME ZONE,
    contribution_amount     DECIMAL,
    group_share_amount      DECIMAL,
    individual_share_amount DECIMAL,
    CONSTRAINT pk_contribution PRIMARY KEY (id)
);

ALTER TABLE contribution
    ADD CONSTRAINT FK_CONTRIBUTION_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);