CREATE TABLE share
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_shares DECIMAL,
    member_id    BIGINT,
    last_updated TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_share PRIMARY KEY (id)
);

ALTER TABLE share
    ADD CONSTRAINT uc_share_member UNIQUE (member_id);

ALTER TABLE share
    ADD CONSTRAINT FK_SHARE_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);