CREATE TABLE loan
(
    loan_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loan_amount      DECIMAL,
    loan_date        TIMESTAMP WITHOUT TIME ZONE,
    repayment_period TIMESTAMP WITHOUT TIME ZONE,
    status           VARCHAR(255)                            NOT NULL,
    member_id        BIGINT,
    CONSTRAINT pk_loan PRIMARY KEY (loan_id)
);

ALTER TABLE loan
    ADD CONSTRAINT FK_LOAN_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);