CREATE TABLE penalty
(
    penalty_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    panalty_date   TIMESTAMP WITHOUT TIME ZONE,
    penalty_amount DECIMAL,
    loan_id        BIGINT,
    CONSTRAINT pk_penalty PRIMARY KEY (penalty_id)
);

ALTER TABLE penalty
    ADD CONSTRAINT FK_PENALTY_ON_LOAN FOREIGN KEY (loan_id) REFERENCES loan (loan_id);