CREATE TABLE repayment
(
    repayment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    repayment_amount DECIMAL,
    interest_paid    DECIMAL,
    principal_paid   DECIMAL,
    loan_id          BIGINT,
    CONSTRAINT pk_repayment PRIMARY KEY (repayment_id)
);

ALTER TABLE repayment
    ADD CONSTRAINT FK_REPAYMENT_ON_LOAN FOREIGN KEY (loan_id) REFERENCES loan (loan_id);