CREATE TABLE "user"
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id BIGINT,
    username  VARCHAR(255),
    password  VARCHAR(255),
    role      SMALLINT,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_member UNIQUE (member_id);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);