CREATE TABLE Groups (
group_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
group_name VARCHAR(255) NOT NULL,
registrationNumber VARCHAR(100) NOT NULL,
group_email VARCHAR(255) NOT NULL,
group_location VARCHAR(255) NOT NULL,
date_registered TIMESTAMP NOT NULL,
postal_address VARCHAR(255) NOT NULL,
group_category VARCHAR(100) NOT NULL,
group_sector VARCHAR(100) NOT NULL,
CONSTRAINT pk_group PRIMARY KEY (group_id)
)