package com.gmatieso.mwanzo.common.utils;

public enum PermissionEnum {

    //  User Enum
    ADMIN_READ("ADMIN_READ"),
    ADMIN_WRITE("ADMIN_WRITE"),
    ADMIN_CREATE("ADMIN_CREATE"),

    TREASURER_READ("TREASURER_READ"),
    TREASURER_WRITE("TREASURER_WRITE"),
    TREASURER_CREATE("TREASURER_CREATE"),

    AUDITOR_READ("AUDITOR_READ"),
    AUDITOR_WRITE("AUDITOR_WRITE"),
    AUDITOR_CREATE("AUDITOR_CREATE"),

    LOAN_OFFICER_READ("LOAN_OFFICER_READ"),
    LOAN_OFFICER_WRITE("LOAN_OFFICER_WRITE"),
    LOAN_OFFICER_CREATE("LOAN_OFFICER_CREATE"),

    CREDIT_COMMITTEE_READ("CREDIT_COMMITTEE_READ"),
    CREDIT_COMMITTEE_WRITE("CREDIT_COMMITTEE_WRITE"),
    CREDIT_COMMITTEE_CREATE("CREDIT_COMMITTEE_CREATE"),

    INDIVIDUAL_MEMBER_READ("INDIVIDUAL_MEMBER_READ"),
    INDIVIDUAL_MEMBER_WRITE("INDIVIDUAL_MEMBER_WRITE"),
    INDIVIDUAL_MEMBER_CREATE("INDIVIDUAL_MEMBER_CREATE"),

    GROUP_REPRESENTATIVE_READ("GROUP_REPRESENTATIVE_READ"),
    GROUP_REPRESENTATIVE_WRITE("GROUP_REPRESENTATIVE_WRITE"),
    GROUP_REPRESENTATIVE_CREATE("GROUP_REPRESENTATIVE_CREATE"),

    GROUP_MEMBER_READ("GROUP_MEMBER_READ"),
    GROUP_MEMBER_WRITE("GROUP_MEMBER_WRITE"),
    GROUP_MEMBER_CREATE("GROUP_MEMBER_CREATE");


    private final String permission;

    PermissionEnum(String permission) { this.permission = permission;
    }

    public String getPermission() {
        return permission;
    }
}
