name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: ✅ Build Complete
      run: echo "Build finished successfully."

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: 🚀 Deploy to AWS EC2
      run: |
        echo "Deploying to EC2..."
        JAR_NAME=$(ls target/*.jar | grep 'Mwanzo-0.0.1-SNAPSHOT.jar' | head -n 1)
        
        # Copy the jar to EC2
        scp -i "${{ secrets.EC2_SSH_KEY }}" -o StrictHostKeyChecking=no $JAR_NAME ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/Mwanzo-0.0.1-SNAPSHOT.jar
        
        # Restart the app
        ssh -i "${{ secrets.EC2_SSH_KEY }}" -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          sudo systemctl stop mwanzo
          sudo systemctl start mwanzo
          sudo systemctl status mwanzo --no-pager
        EOF
